title: Try Mode 2.0
description: A modified Try Mode Map for Heroes of the Storm to create a better experience with enhanced functionalities.
repository: jamiephan/HeroesOfTheStorm_TryMode2.0
theme: just-the-docs

# To test locally:
# cd docs
# bundle install
# bundle exec jekyll serve

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap
  
tagline: A modified Try Mode Map for Heroes of the Storm
baseurl: /HeroesOfTheStorm_TryMode2.0
google_site_verification: OKKzM2WHK1hiYsONJfxwRDvo-iSydAZPpXonNgcoxWY
markdown: kramdown
# mermaid:
#   version: "9.1.6"
aux_links:
  "Try Mode 2.0 on GitHub":
    - "https://github.com/jamiephan/HeroesOfTheStorm_TryMode2.0"

# nav_external_links:
#   - title: Try Mode 2.0 Repo
#     url: "https://github.com/jamiephan/HeroesOfTheStorm_TryMode2.0"
#   - title: Try Mode 2.0 Installer Repo
#     url: "https://github.com/jamiephan/HeroesOfTheStorm_TryMode2.0Installer"
#   - title: Heroes Gamedata Repo
#     url: "https://github.com/jamiephan/HeroesOfTheStorm_Gamedata"
#   - title: Heroes S2MA Repo
#     url: "https://github.com/jamiephan/HeroesOfTheStorm_S2MA"
#   - title: Heroes AI Maps Repo
#     url: "https://github.com/jamiephan/HeroesOfTheStorm_AIMaps"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: 'Try Mode 2.0 is a personal project and is not affiliated, associated, authorized, endorsed by, or in any way officially connected with Blizzard or Heroes of the Storm. Distributed by an <a href="https://github.com/jamiephan/HeroesOfTheStorm_TryMode2.0Installer/blob/main/LICENSE">MIT license.</a>'
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/jamiephan/HeroesOfTheStorm_TryMode2.0" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 6
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s\-\|\(\)/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: true
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: "k"

color_scheme: trymode20

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

enable_copy_code_button: true
