title: Heroes of the Storm - Try Mode 2.0
description: A modified Try Mode Map for Heroes of the Storm to create a better experience with enhanced functionalities.
theme: jekyll-theme-cayman
gems:
  - jekyll-seo-tag
tagline: A modified Try Mode Map for Heroes of the Storm
google_site_verification: OKKzM2WHK1hiYsONJfxwRDvo-iSydAZPpXonNgcoxWY


