name: create-release
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'README.md'
jobs:
  Release:
    name: Creating a Release on Github
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
      - name: Install Dependencies
        run: npm install
      - name: Build and Patch Maps
        run: npm run ci:patchmaps
        env:
          OUTPUT_DIR: C:/maps
      - name: Create Github Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: release-${{ github.event.head_commit.id }}
          name: ${{ github.event.head_commit.message }}
          body: |
            Commit Message: `${{ github.event.head_commit.message }}`

            Built time: `${{ github.event.head_commit.timestamp }}`

            Maps with the name `.AI` indicates the map will be filled with AI players.

            For instructions on how to run the maps below, Please refer to [installation guide](https://jamiephan.github.io/HeroesOfTheStorm_TryMode2.0/install.html).
          draft: false 
          prerelease: false
          files: "C:/maps/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}